//PRODUCTOS.ROUTES

const { Router } = require('express');
const { check  } = require('express-validator');



//ENDPOINT PARA CREAR PRODUCTOS


//ENDPOINT PARA OBTENER TODOS LOS PRODUCTOS

//ENDPOINT PARA OBTBER UN PRODUCTO POR SU ID


//ENDPOINT PARA ACTUALIZAR UN PRODUCTO

//ENDPOINT PARA ELIMINAR UN PRODUCTO